// eslint-disable-next-line
export const LIST_ACTIONS = {
  ALL_MANGA_UPDATE_LIST: "ALL_MANGA_UPDATE_LIST",
  MANGA_SELECT_FOR_DOWNLOAD: "MANGA_SELECT_FOR_DOWNLOAD",
  MANGA_ADD: "MANGA_ADD",
  MANGA_CLEAR: "MANGA_CLEAR",
  MANGA_SEARCH: "MANGA_SEARCH",
  MANGA_UPDATE_LIST: "MANGA_UPDATE_LIST",
  SET_FILTER_VALUE: "SET_FILTER_VALUE",
  DOWNLOAD_MANGA: "DOWNLOAD_MANGA",
  CHAPTER_TOGGLE: "CHAPTER_TOGGLE",
  CHAPTER_SELECT_ALL: "CHAPTER_SELECT_ALL",
  CHAPTER_UNSELECT_ALL: "CHAPTER_UNSELECT_ALL",
  CHAPTER_SELECT_RANGE: "CHAPTER_SELECT_RANGE",
  SET_DOWNLOAD_MANGA_FILTER_VALUE: "SET_DOWNLOAD_MANGA_FILTER_VALUE",
  SET_DOWNLOAD_MANGA_STATUS: "SET_DOWNLOAD_MANGA_STATUS",
  ADD_DOWNLOADED_CHAPTER: "ADD_DOWNLOADED_CHAPTER",
  SET_MANGA_INFO_IS_FETCHING: "SET_MANGA_INFO_IS_FETCHING",
  SET_GLOBAL_MESSAGE: "SET_GLOBAL_MESSAGE",
  REMOVE_GLOBAL_MESSAGE: "REMOVE_GLOBAL_MESSAGE"
};
