// eslint-disable-next-line
export const LIST_ACTIONS = {
  MANGA_SELECT_FOR_DOWNLOAD: "MANGA_SELECT_FOR_DOWNLOAD",
  MANGA_ADD: "MANGA_ADD",
  MANGA_CLEAR: "MANGA_CLEAR",
  MANGA_SEARCH: "MANGA_SEARCH",
  SET_FILTER_VALUE: "SET_FILTER_VALUE",
  DOWNLOAD_MANGA: "DOWNLOAD_MANGA",
  CHAPTER_TOGGLE: "CHAPTER_TOGGLE",
  CHAPTER_SELECT_ALL: "CHAPTER_SELECT_ALL",
  CHAPTER_UNSELECT_ALL: "CHAPTER_UNSELECT_ALL",
  CHAPTER_SELECT_RANGE: "CHAPTER_SELECT_RANGE"
};
