export const SETTINGS_ACTIONS = {
  SET_SETTINGS: "SET_SETTINGS",
  SET_UPDATE_ON_START: "SET_UPDATE_ON_START",
  SET_DEFAULT_SAVE_LOCATION: "SET_DEFAULT_SAVE_LOCATION",
  SET_DEFAULT_FORMAT: "SET_DEFAULT_FORMAT",
  SET_NOTIFY_ON_FINISH: "SET_NOTIFY_ON_FINISH",
  SET_DARK_THEME: "SET_DARK_THEME"
};
